// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class Quiptionary
{
	// entries in arrays need to end with a comma
	public static string[] Quips = 
	new string[]{
		"this is a%n example of a qu%ick time event",
		"with mo%re than a sin%gle entry in it",
	};

	public static string[] Nouns =
	new string[]{
		"apple",
		"potato",
	};

	public static string[] Verbs = 
	new string[]{
		""
	};

	public static string[] Adjectives =
	new string[]{
		""
	};
	public Quiptionary()
	{
	}
}

