// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class Quiptionary
{
	// entries in arrays need to end with a comma
	public static string[] Quips = 
	new string[]{
		"Thy ve%ry nearn%ess makes me ret%ch!",
		"Your finest rep%ast is my foul%est movem%ent",
		"One must b%e of easy vir%tue to procure such lux%ury!",
		"May thy offs%pring be prof%oundly uncome%ly!",
		"Doth thy usu%ally reek of mi%re and cow%plop?",
		"Thine ha%ir is like fo%ul loin fri%nge!",
		"Thou art wo%rth less than th%at of the ord%ure you pro%duce!",
		"Thine sense o%f sarto%rial flair has bur%ned sig%ht from my eyes!",
		"Thine presen%ce blocks lig%ht like an as%s dark%ens a bo%wl!",
		"Thine voice is mu%sic of a mo%st foul inter%ior movem%ent!",
		"Hast your pers%onal carri%age heaved foul win%ds in my direc%tion",
		"Dost thou sme%ll of taw%dry copula%tion at all ho%urs?",
		"Begone, filthy whelp%! I have no use for a mam%mering, lump%ish trol%lop such as you!",
		"Thy hair is as fo%ul as a pox-%marked bov%ine!",
		"Hast thou been tou%ched by a pla%gue of doltishne%ss, you mewling peas%ant?",
		"Thou ar%t as den%se as thou art hom%ely, you putrid poten%tate!",
		"Thy dre%ss is so monst%rous; its seamstr%ess must have been born bl%ind in a cave with infe%cted, goa%tish hands!",
		"Thy grues%ome visa%ge robs me of all rea%son!",
		"A shrill%er, more mac%bre note, could not be str%uck except by th%y own voice!",
		"A crueller, more har%sh punis%hment than spe%nding another moment wi%th thou could not be conce%ived!",
		"Thy own paren%tage is but a de%n of swine and ince%st!",
		"An abat%toir keeps bet%ter company than th%ou!",
		"Your mot%her is a fro%thing troll%op!",
		"The horr%or that thou say%eth is wor%se than the horr%or you excr%ete!",
		"Art thee dens%er than darkest matt%er, or art thou a crea%ture of dim%mer cor%uscation?",
		"Art thou too ba%se for mine own rhap%sodic rhet%oric?",
		"Were you to cea%se consuming comes%tible goods, the poor would fea%st like roya%lty for etern%ity!",
		"I would pr%ay to lis%ten to thy quibb%ling cho%ps, but I art remi%nded of mois%t vaginal win%ds!",
		"Get the%e to a nun%nery, go%!",
		"The tart%ness of your face sour%s ripe gra%pes!",
		"Thy as%s is spher%ical, like a glo%be. I cou%ld find count%ries on it.",
		"Thou art of clo%ven hoof and wall%owing pau%per progenat%ion!",
		"Even my go%wn makes thi%ne ass unfathomab%le; as if one could be adr%ift in wav%es of fulsome fa%t!",



	};

	public static string[] Nouns =
	new string[]{
		
		"barnacle",
		"bugbear",
		"codpiece",
		"foot-licker",
		"haggard",
		"harpy",
		"lewdster",
		"lout",
		"miscreant",
		"strumpet",
		"swine",
		"vassal",
		"wagtail",
		"felon",
		"bastard",
		"hag",
		"halfwit",
		"horeson",
		"shrew",
		"wench",
		"wretch",
		"canker",
		"hell-spawn",
		"sod",
		"ingrate",
		"knave",
		"puritan",
		"braggart",
		"scamp",
		"scullion",
		"snake",
		"scoundrel",
		"rapscallion",
		"rake",
		"pauper",
		"worm",
		"beggar",
		"brute",
		"vagrant",
		"sycophant",

	};

	public static string[] Verbs = 
	new string[]{
		
		"Heaving",
		"Jack-Knifing",
		"Buggering",
		"Hornswaggling",
		"Transforming",
		"Flying",
		"Doting(love)",
		"Stymied",
		"Gibbering ",
		"Grovelling ",
		"Gasping",
		"Gaping",
		"Frothing",
		"Cowering",
		"Double-Crossing",
		"Leaping",
		"Basting",
		"Basted",
		"Unbecoming",
		"Frightened",
		"Prating",
		"Vacillating",
		"Gesticulating",
		"Wallowing",


	};

	public static string[] Adjectives =
	new string[]{
		"artless",
		"afeared",
		"arrant",
		"bawdy",
		"bootless",
		"boot-licking",
		"cockered",
		"craven",
		"crafty",
		"dankish",
		"droning",
		"errant",
		"fawning",
		"fool-born",
		"frothy",
		"goatish",
		"ill-bred",
		"impertinent",
		"infectious",
		"jarring",
		"lumpish",
		"mammering",
		"mangled",
		"mewling",
		"paunchy",
		"puny",
		"rank",
		"rhapsodic",
		"roguish",
		"ruttish",
		"saucy",
		"surly",
		"superfluous",
		"tawdry",
		"tottering",
		"vain",
		"venomed",
		"villainous",
		"wayward",
		"weedy",
		"dog-hearted",
		"milk-livered",
		"pox-marked",
		"sheep-biting",
		"rump-fed",
		"toad-spotted",
		"swag-bellied",
		"fly-bitten",
		"elf-skinned",
		"common-kissing",
		"beef-witted",
	};
	public Quiptionary()
	{
	}
}

